### ISSUE TITLE
reverse string is not equivalent in rust. Correct code.

### ISSUE THREAD

**Issue by PauloCotrim** [yzhang71/Rust_C_Benchmarks#1]
pub fn reverse(chars:  &mut Vec<char>, len: usize) {
    let mut i = 0;
    let mut j = len - 1;
    
    while i < j {
        chars.swap(i, j);
        i = i + 1;
        j = j - 1;
    }
} 

use std::io::stdin;
use std::time::Instant; 

fn main() {
    //Declare a mutable input string
    let mut input_string = String::new();
    stdin().read_line(&mut input_string)
        .ok()
        .expect("");                
           
    let len = input_string.len();
    let mut input_string: Vec<_> = input_string.chars().collect();
    
    let start = Instant::now();
    for _i in 0..100000000 {
        reverse(&mut input_string, len);
    }
    let duration = start.elapsed();

    println!("Time elapsed is: {:?}", duration);
}

**Comment by yzhang71** [comment]
Hi Paulo, thank you for the correction. Your change makes sense, and the vector initialization `(let mut chars: Vec<_> = text.chars().collect();)` should indeed be moved out of the reverse function. It would be great if you could create a pull request with the corrected code, and I will approve it.
